### ISSUE TITLE
Not able to run REPL

### ISSUE THREAD

**Issue by saikrishna321** [Jonahss/AppiumRepl#5]
@Jonahss 

I tried as per instruction, i get the below error . Can you please help me

 AppiumRepl-master  node . ContactManager
module.js:338
    throw err;
          ^
Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/saikrisv/Downloads/AppiumRepl-master/lib/appium-repl.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by Jonahss** [comment]
run `npm install colors`

I'll update this module so that it works better :)

**Comment by saikrishna321** [comment]
@Jonahss need help .. 

 i was able to launch the app from REPL but when i interact with elements i get undefined as below 

elm = driver.elementById("org.wordpress.android:id/nux_password");
 > CALL elementById("org.wordpress.android:id/nux_password") 
undefined
("o") > RESPONSE elementById("org.wordpress.android:id/nux_password") {"ELEMENT":"7"}

**Comment by Jonahss** [comment]
Ahh, the driver is returning promises. So you need to get its response. Check out the source code and play with wd.js :)

**Comment by saikrishna321** [comment]
@Jonahss completely dint get that .. i see appium-repl.js not wd.js in the repo

**Comment by millenniummike** [comment]
driver.elementByName('Allow').then(function(result){button=result})
click.button()
